### ISSUE TITLE
Question : Monitoring Sync replication

### ISSUE THREAD

**Issue by pcamelio** [tomcz/openldap_exporter#20] opened 2022-05-16 08:36 UTC
Hello,
How --replicationObject is supposed to work ?

I made some try to monitor "dc=domain,dc=local" and I have the following error message 
WARN[0030] query failed                                  component=scraper error="LDAP Result Code 4 \"Size Limit Exceeded\": " filter="(objectClass=*)"

I understand the errror, but  not the expected syntax

Best regards

**Comment by tomcz** [comment] 2022-08-13 20:46
@JGodin-C2C can you help?

**Comment by JGodin-C2C** [comment] 2022-08-15 06:35
Yup @tomcz , sure !
Hello @pcamelio , your syntax seems to be correct.
Could you try this query by hand and try to reproduce  the behaviour "by hand" on your installation ?

`ldapsearch -x -LLL -H ldap://localhost -s base -b dc=domain,dc=local contextcsn `

Note that the base should be the replicated content. 

J\x00

**Comment by tiago-cruz-movile** [comment] 2023-01-06 20:47
Hey, in my case

```
dn: dc=datac,dc=xxx,dc=com
contextCSN: 20230104171052.895118Z#000000#001#000000
contextCSN: 20230106202836.142061Z#000000#00b#000000
```

I'm getting
```
openldap_monitor_replication{id="001",type="count"} 0
openldap_monitor_replication{id="001",type="gt"} 1.672855957e+09
openldap_monitor_replication{id="001",type="mod"} 0
```

But i'm interested to get information about `#00b#` and not `#001#` is this possible?

**Comment by JGodin-C2C** [comment] 2023-01-10 15:23
This as nothing to do with original request. 
Please open a new one. 
@tomcz can you "close" this request please ? I guess the original question have been answered.

**Comment by JGodin-C2C** [comment] 2023-01-20 14:53
@tomcz You can close this .

**Comment by pcamelio** [comment] 2023-01-20 14:57
Hi guys
Sorry for the delay.
I haven't  tested, but you can close the case.

**Comment by tomcz** [comment] 2023-01-20 17:03
Thank you.

**Closed as completed by tomcz** 2023-01-20 17:03 UTC
