### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by kumy** [tomcz/openldap_exporter#2] opened 2019-01-09 17:54 UTC
May it be possible to implement TLS connection to OpenLdap server?

**Comment by kumy** [comment] 2019-01-16 09:57
@tomcz Please see PR #3

**Comment by scatenag** [comment] 2020-08-03 13:49
@kumy 
I tried your version with my openldap installation

```
git clone --single-branch --branch issue-2 https://github.com/kumy/openldap_exporter.git
cd openldap_exporter/
make deps
make build
cd target/
 ./openldap_exporter-linux -ldapSkipInsecure  -ldapUser cn=monitor,dc=it  -ldapPass monitor223 -ldapUri "ldap://address:389"
```
but I get 
```
2020/08/03 15:40:07 Starting prometheus HTTP metrics server on :9330
2020/08/03 15:40:07 Starting OpenLDAP scraper for ldap://address:389
2020/08/03 15:40:37 Scrape failed, error is: LDAP Result Code 13 "Confidentiality Required": confidentiality required

```

I think the problem is that my server use TLS over `ldap://` with start_tls (not `ldaps://`  [which, I think, is deprecated](https://www.openldap.org/faq/data/cache/605.html)).

My standard working query is
 
`LDAPTLS_REQCERT=never ldapsearch -x -H ldap://address -ZZ -D cn=monitor,dc=it -w password -b cn=Uptime,cn=Time,cn=Monitor -s base '(objectClass=*)' '*' '+'`

please note the `ldap:// `uri and the `-ZZ` (start tls).

Do you have any thoughts to make them working ?

**Comment by kumy** [comment] 2020-08-03 14:05
@scatenag I don't think PR #3 add support for `StartTLS`, but only "full" TLS.

For that I think some lines should be added after line 131
https://github.com/tomcz/openldap_exporter/blob/c27f926b4b374e9d6ae555457a23a9385b3d1546/code/src/app/exporter/scraper.go#L131

According to the [doc](https://godoc.org/gopkg.in/ldap.v2#Conn.StartTLS) something like this should be sufficient:
```go
// Reconnect with TLS
err = l.StartTLS(&tls.Config{InsecureSkipVerify: true})
if err != nil {
    log.Fatal(err)
}
```

You may wish to add some logic (a new command parameter) to have it activatable on demand :smile:

**Comment by scatenag** [comment] 2020-08-03 22:16
Great!! It is working !! 

I have seen just now that also [PR#5](https://github.com/tomcz/openldap_exporter/pull/5) adds support for TLS with startTLS, but it lacks of `-ldapSkipInsecure` (that is, `LDAPTLS_REQCERT=never`) ...

For the moment I will use this PR with this small modification
(trying to write something for a new command parameter to make it activable on demand - I am new to go) ... 
...then I will see how to merge the two PR into a new one 
(hoping that one of these will be merged).

Thanks!!

**Closed as completed** 2021-12-31 09:55 UTC
